name = "analytics-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = ""
workers_dev = true

[env.production]
name = "analytics-worker-production"
routes = [
  { pattern = "coryd.dev/js/*", zone_id = "" },
  { pattern = "coryd.dev/api/event", zone_id = "" }
]