export default [
  { "name": "Adam Newbold", "url": "https://notes.neatnik.net", "feed": "https://notes.neatnik.net", "description": "Everything Adam makes is amazing (including omg.lol, of course)." },
  { "name": "Ashur Cabrera", "url": "https://multiline.co/mment", "feed": "https://multiline.co/mment/feed.xml", "description": "An excellent writer and a must follow for content both technical and otherwise." },
  { "name": "Chris Burnell", "url": "https://chrisburnell.com", "feed": "https://chrisburnell.com/feed.xml", "description": "A whole host of useful posts on CSS, JavaScript and other technical topics." },
  { "name": "Chris Coyier", "url": "https://chriscoyier.net", "feed": "https://chriscoyier.net/feed/", "description": "A prolific writer and posts about a wide range of topics, including web development, CSS and more." },
  { "name": "Chris McLeod", "url": "https://chrismcleod.dev", "feed": "https://chrismcleod.dev/feed.xml", "description": "A beautifully designed blog full of content covering everything from Warhammer to the indie web." },
  { "name": "fLaMEd", "url": "https://flamedfury.com", "feed": "https://flamedfury.com/feed.xml", "description": "Awesome retro and small web content — plus the design of the is awesome." },
  { "name": "Joe Steel", "url": "https://joe-steel.com", "feed": "https://joe-steel.com/feed.xml", "description": "Joe blogs about tech, the perpetually abysmal state of Apple's TV and movie products and numerous other things." },
  { "name": "Keenan", "url": "https://gkeenan.co/avgb", "feed": "https://gkeenan.co/avglb?format=rss", "description": "If you don't love them it's because you don't yet know them — a fantastic writer too." },
  { "name": "Kev Quirk", "url": "https://kevq.uk", "feed": "https://kevq.uk/feed.xml", "description": "One of the admins of fosstodon.org and author of a really great blog." },
  { "name": "Łukasz Wójcik", "url": "https://lukaszwojcik.net", "feed": "https://blog.lukaszwojcik.net/full.xml", "description": "Posts about tech, web development and Eleventy. Łukasz is a talented and kind engineer." },
  { "name": "Matt Birchler", "url": "https://birchtree.me", "feed": "https://birchtree.me/rss/", "description": "Matt is exceedingly kind and also posts about Apple, tech and other topics." },
  { "name": "Mike Haynes", "url": "https://crashthearcade.com", "feed": "https://crashthearcade.com/feed/rss", "description": "A beautifully-designed site and I enjoy Mike's commentary and writing." },
  { "name": "Nick Heer", "url": "https://pxlnv.com", "feed": "https://feedpress.me/pxlnv", "description": "A must-follow for anyone interested in Apple and tech." },
  { "name": "Paul Anthony Webb", "url": "https://webb.page", "description": "One of the coolest, most unique personal sites around." },
  { "name": "Raymond Camden", "url": "https://raymondcamden.com", "feed": "https://www.raymondcamden.com/feed.xml", "description": "Raymond covers a wide, wide range of web development topics and never fails to provide both insight and clarity." },
  { "name": "Robb Knight", "url": "https://rknight.me", "feed": "https://rknight.me/subscribe/posts/rss.xml", "description": "Robb has the coolest site on the web and is an all around awesome dude." },
  { "name": "Sia Karamalegos", "url": "https://sia.codes", "feed": "https://sia.codes/feed/feed.xml", "description": "An accomplished speaker and writer, Sia's blog is full of useful posts on a wide array of development topics." },
  { "name": "Stephanie Eckles", "url": "https://thinkdobecreate.com", "feed": "https://thinkdobecreate.com/feed", "description": "Myriad helpful and easy to understand resources to learn CSS and numerous other web development topics." },
  { "name": "Zach Leatherman", "url": "https://www.zachleat.com", "feed": "https://www.zachleat.com/web/feed/", "description": "Eleventy's creator who posts handy content about the framework, web components and web development writ large." }
]