export default [
  'AdsBot-Google',
  'Amazonbot',
  'anthropic-ai',
  'Arc',
  'ArcMobile2',
  'Bytespider',
  'CCBot',
  'ChatGPT-User',
  'cohere-ai',
  'FacebookBot',
  'Google-Extended',
  'GPTBot',
  'omgili',
  'Omgilibot',
  'PerplexityBot',
  'YouBot',
]