###
# PLUGINS
###
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    url = "https://coryd.dev"
  [plugins.inputs.audits]
    output_path = "lighthouse.html"

###
# URLs
###
[build.processing.html]
  pretty_urls = true

###
# HEADERS
###
[[headers]]
for = "/feeds/posts"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/feeds/links"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/feeds/books"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/feeds/follow"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/.well-known/webfinger"
  [headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
for = "/.well-known/gpc.json"
  [headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
for = "/.well-known/traffic-advice"
  [headers.values]
  Content-Type = "application/trafficadvice+json"

[[headers]]
for = "/contribute.json"
  [headers.values]
  Content-Type = "application/json"

[[headers]]
    for = "/*"
    [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"