###
# PLUGINS
###
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

###
# URLs
###
[build.processing.html]
  pretty_urls = true

###
# HEADERS
###
[[headers]]
for = "/feed.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/links.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/books.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/follow.xml"

  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/.well-known/webfinger"
  [headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
for = "/.well-known/gpc.json"
  [headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
for = "/.well-known/traffic-advice"
  [headers.values]
  Content-Type = "application/trafficadvice+json"

[[headers]]
for = "/contribute.json"
  [headers.values]
  Content-Type = "application/json"