###
# PLUGINS
###
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    url = "https://coryd.dev"
    output_path = "reports/lighthouse.html"

###
# URLs
###
[build.processing.html]
  pretty_urls = true

###
# HEADERS
###
[[headers]]
for = "/feeds/posts"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/feeds/links"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/feeds/books"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/feeds/follow"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/.well-known/webfinger"
  [headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
for = "/.well-known/gpc.json"
  [headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
for = "/.well-known/traffic-advice"
  [headers.values]
  Content-Type = "application/trafficadvice+json"

[[headers]]
for = "/contribute.json"
  [headers.values]
  Content-Type = "application/json"