###
# PLUGINS
###
[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache", "./src/assets/img/cache" ]

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse/index.html"

###
# OPTIMIZATION
###
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.images]
  compress = true

###
# URLs
###
[build.processing.html]
  pretty_urls = true

###
# HEADERS
###
[[headers]]
for = "/feed.xml"

  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/links.xml"

  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/follow.xml"

[headers.values]
  Content-Type = "application/xml; charset=utf-8"
  x-content-type-options = "nosniff"

[[headers]]
for = "/.well-known/webfinger"

[headers.values]
  Content-Type = "application/jrd+json; charset=utf-8"

###
# SITE REDIRECTS
###
[[redirects]]
from = "/rss.xml"
to = "/feed.xml"
status = 301

[[redirects]]
from = "/blog/fixing-safari-icloud-syncing"
to = "/posts/2022/fixing-safari-icloud-syncing/"
status = 301

[[redirects]]
from = "/blog/migrating-to-fastmail"
to = "/posts/2022/migrating-to-fastmail/"
status = 301

[[redirects]]
from = "/blog/client-side-webmentions-in-nextjs"
to = "/posts/2023/client-side-webmentions-in-nextjs/"
status = 301

[[redirects]]
from = "/blog/apple-centric-digital-privacy-tools"
to = "/posts/2022/apple-centric-digital-privacy-tools/"
status = 301

[[redirects]]
from = "/blog/automating-rss-syndication-with-nextjs-github"
to = "/posts/2023/automating-rss-syndication-with-nextjs-github/"
status = 301

[[redirects]]
from = "/blog/apple-music-a-tale-of-woe"
to = "/posts/2021/apple-music-a-tale-of-woe/"
status = 301

[[redirects]]
from = "/blog/adding-client-side-rendered-webmentions-to-my-blog"
to = "/posts/2023/client-side-webmentions-in-nextjs/"
status = 301

[[redirects]]
from = "/blog/automating-email-cleanup-in-gmail"
to = "/posts/2022/automating-email-cleanup-in-gmail/"
status = 301

[[redirects]]
from = "/blog/fastmail-handling-inbound-email-with-regex-filters-now-with-chatgpt"
to = "/posts/2023/fastmail-handling-inbound-email-with-regex-filters-now-with-chatgpt/"
status = 301

[[redirects]]
from = "/blog/simple-api-fetch-hooks-with-swr"
to = "/posts/2022/simple-api-fetch-hooks-with-swr/"
status = 301

[[redirects]]
from = "/2023/02/automatingandprobablyoverengineeringmy-nowpage"
to = "/posts/2023/automating-and-overengineering-my-now-page/"
status = 301

[[redirects]]
from = "/2023/01/workflows-handling-inbound-email-on-fastmail-with-regular-expressions"
to = "/posts/2023/fastmail-handling-inbound-email-with-regex-filters-now-with-chatgpt/"
status = 301