backend:
  name: git-gateway
  branch: main
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "YYYY/title.md"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DDTHH:MM-08:00", format: "YYYY-MM-DDTHH:MM-08:00"}
      - {label: "tags", name: "tags", widget: "list", default: ["posts"]}
      - {label: "Body", name: "body", widget: "markdown"}