name = "now-playing-worker"
main = "./index.js"  # Specify the entry point
compatibility_date = "2023-01-01"

account_id = ""
workers_dev = true

[env.production]
name = "now-playing-worker-production"
routes = [
  { pattern = "coryd.dev/api/now-playing", zone_id = "" }
]