CREATE OR REPLACE VIEW three_month_tracks AS
SELECT
    ol.id,
    ol.listened_at,
    ol.track_name,
    ol.artist_name,
    ol.album_name,
    ol.album_key,
    ol.artist_art,
    ol.artist_genres,
    ol.genre_name,
    ol.artist_country,
    ol.album_art,
    ol.artist_url,
    ol.genre_url
FROM
    optimized_listens ol
WHERE
    TO_TIMESTAMP(ol.listened_at) >= NOW() - INTERVAL '3 months'
ORDER BY
    TO_TIMESTAMP(ol.listened_at) DESC;