name = "scrobble-worker"
main = "./index.js"
compatibility_date = "2023-01-01"

account_id = ""
workers_dev = true

[env.production]
name = "scrobble-worker-production"
routes = [
  { pattern = "coryd.dev/api/scrobble*", zone_id = "" }
]
