export default {
  "https://www.theguardian.com": "The Guardian",
  "https://www.newyorker.com": "The New Yorker",
  "https://ploum.net": "Ploum.net",
  "https://www.businessinsider.com": "Business Insier",
  "https://ergaster.org": "Thibault Martin",
  "https://www.oddbird.net": "OddBird",
  "https://chrishannah.me": "Chris Hannah",
  "https://robinrendle.com": "Robin Rendle",
  "https://www.nngroup.com": "Nielsen Norman Group",
  "https://www.vulture.com": "Vulture",
  "https://blog.danslimmon.com": "Dan Slimmon",
  "https://freddiedeboer.substack.com": "Freddie deBoer",
  "https://educatedguesswork.org": "Eric Rescorla",
  "https://www.theprivacywhisperer.com": "Luiza Jarovsky",
  "https://www.matuzo.at": "Manuel Matuzović",
  "https://theoutline.com": "The Outline",
  "https://esif.dev": "Educational Sensational Inspirational Foundational",
  "https://chriscoyier.net": "Chris Coyier",
  "https://everythingchanges.us": "Mandy Brown",
  "https://addyosmani.com": "Addy Osmani",
  "https://thehistoryoftheweb.com": "The History of the Web",
  "https://css-tricks.com": "CSS Tricks",
  "https://www.latimes.com": "The LA Times",
  "https://seldo.com": "There's no such thing as the fundamentals of web development | Seldo.com",
  "https://defector.com": "Defector",
  "https://heather-buchel.com": "Heather Buchel",
  "https://blog.thecodewhisperer.com": "J. B. Rainsberger",
  "https://thehardtimes.net": "Dan Rice",
  "https://www.invisibleoranges.com": "Invisible Oranges",
  "https://nazhamid.com": "Naz Hamid",
  "https://ethanmarcotte.com": "Ethan Marcotte",
  "https://blog.jim-nielsen.com": "Jim Nielsen",
  "https://lucybellwood.com": "Lucy Bellwood",
  "https://dev.to": "Dev.to Community",
  "https://karawynn.substack.com": "Karawynn Long",
  "https://leahreich.substack.com": "Leah Reich",
  "https://erinkissane.com": "Erin Kissane",
  "https://www.smashingmagazine.com": "Smashing Magazine",
  "https://rknight.me": "Robb Knight",
  "https://stephanango.com": "Steph Ango",
  "https://pxlnv.com": "Nick Heer",
  "https://jacobin.com": "Jacobin",
  "https://www.techdirt.com": "TechDirt",
  "https://www.zachleat.com": "Zach Leatherman",
  "https://derekkedziora.com": "Derek Kedziora",
  "https://www.afterbabel.com": "Freya India",
  "https://jenniferplusplus.com": "Jennifer Moore",
  "https://www.wired.com": "Wired",
  "https://blog.j11y.io": "James Padolsey",
  "https://www.hunker.com": "Hunker",
  "https://www.htmhell.dev": "HTMHell",
  "https://blakewatson.com": "blakewatson.com  –  omg.lol: an oasis on the internetImported Layers",
  "https://www.ursulakleguin.com": "Ursula K. Le Guin",
  "https://pepelsbey.dev": "Vadim Makeev",
  "https://slate.com": "Slate",
  "https://adrianroselli.com": "Adrian Roselli",
  "https://manuelmoreale.com": "Manu Moreale",
  "https://frontside.com": "Frontside",
  "https://xeiaso.net": "Xe Iaso",
  "https://locusmag.com": "Locus",
  "https://wheresyoured.at": "Ed Zitron",
  "https://jacobian.org": "Jacob Kaplan-Moss",
  "https://danmcquillan.org": "Dan Mcquillan",
  "https://gkeenan.co": "Keenan",
  "https://fsfe.org": "FSFE",
  "https://pdx.su": "Jeff Sandberg",
  "https://chrismcleod.dev": "Chris McLeod",
  "https://flamedfury.com": "fLaMEd",
  "https://www.rollingstone.com": "Anil Dash",
  "https://multiline.co": "Multiline Comment",
  "https://thebaffler.com": "The Baffler",
  "https://www.mayank.co": "Mayank",
  "https://benmyers.dev": "Ben Myers",
  "https://infrequently.org": "Alex Russell",
  "https://12daysofweb.dev": "12 Days of Web",
  "https://www.scientificamerican.com": "Scientific American",
  "https://cdevroe.com": "Colin Devroe",
  "https://tomcritchlow.com": "Tom Critchlow",
  "https://deathtobullshit.com": "Death to Bullshit",
  "https://eftegarie.com": "Amin Eftegarie",
  "https://library.xandra.cc": "the library of alexandra",
  "https://notebook.wesleyac.com": "Wesley Aptekar-Cassels",
  "https://24ways.org": "24 ways",
  "https://www.daniel.pizza": "Daniël van der Winden",
  "https://www.thejaymo.net": "Jay Springett",
  "https://dariusforoux.com": "Darius Foroux",
  "https://briankoberlein.com": "Brian Koberlein",
  "https://benhoyt.com": "Ben Hoyt",
  "https://atthis.link": "Marc",
  "https://ar.al": "Aral Balkan",
  "https://maerk.xyz": "Mark",
  "https://newrepublic.com": "Gil Duran",
  "https://prospect.org": "David Dayen",
  "https://gilest.org": "Giles Turnbull",
  "https://www.jackcheng.com": "Jack Cheng",
  "https://fromjason.xyz": "Jason Velazquez",
  "https://www.fromjason.xyz": "JASON VELAZQUEZ",
  "https://meyerweb.com": "Eric A. Meyer",
  "https://citationneeded.news": "Molly White",
  "https://hypercritical.co": "John Siracusa",
  "https://thathtml.blog": "Jared White",
  "https://proton.me": "Proton",
  "https://blog.cassidoo.co": "Cassidy Williams",
  "https://www.cassey.dev": "Cassey Lottman",
  "https://doctorow.medium.com": "Cory Doctorow",
  "https://jaredwhite.com": "Jared White",
  "https://remotesynthesis.com": "Remote Synthesis",
  "https://inessential.com": "Brent Simmons",
  "https://read.engineerscodex.com": "Leonardo Creed",
  "https://waxy.org": "Andy Baio",
  "https://www.anildash.com": "Anil Dash",
  "https://macwright.com": "Tom MacWright",
  "http://maerk.xyz": "Mark",
  "https://www.spacebar.news": "the spacebar",
  "https://johan.hal.se": "Johan Halse",
  "https://joanwestenberg.com": "Joan Westenberg",
  "https://zachholman.com": "Zach Holman",
  "https://jakelazaroff.com": "Jake Lazaroff",
  "https://cloudfour.com": "Cloud Four",
  "https://joe-steel.com": "Joe Rosensteel",
  "https://aworkinglibrary.com": "Mandy Brown",
  "https://max.engineer": "Max Chernyak",
  "https://hamatti.org": "Juha-Matti Santala",
  "https://blog.carlana.net": "Carlana Johnson",
  "https://darkvisitors.com": "Dark Visitors",
  "https://gomakethings.com": "Chris Ferdinandi",
  "https://www.wheresyoured.at": "Ed Zitron",
  "https://httpster.io": "Sami",
  "https://www.tylerjfisher.com": "Tyler Fisher",
  "https://www.baldurbjarnason.com": "Baldur Bjarnason",
  "https://lmnt.me": "Louie Mantia",
  "https://www.lrb.co.uk": "London Review of Books",
  "https://piccalil.li": "Andy Bell",
  "https://robhorning.substack.com": "Rob Horning",
  "https://explodingcomma.com": "Exploding Comma",
  "https://mikegrindle.com": "Mike Grindle",
  "https://garden.mattstein.com": "Matt Stein",
  "https://notes.neatnik.net": "Adam Newbold",
  "https://frills.dev": "Frills",
  "https://iamfran.com": "Fran",
  "https://www.citationneeded.news": "Molly White",
  "https://www.musicbusinessworldwide.com": "Music Business Worldwide",
  "https://joshcollinsworth.com": "Josh Collinsworth",
  "https://collider.com": "Chase Hutchinson",
  "https://bastianallgeier.com": "Bastian Allgeier",
  "https://storyfair.net": "Sean Hinn",
  "https://nuejs.org": "Nue",
  "https://whitep4nth3r.com": "Salma Alam-Naylor",
  "https://www.garbageday.email": "Ryan Broderick",
  "https://lynnandtonic.com": "Lynn Fisher",
  "https://blog.lukaszwojcik.net": "Łukasz Wójcik",
  "https://ohhelloana.blog": "Ana Rodrigues",
  "https://tonsky.me": "Nikita Prokopov",
  "https://blog.chriszacharias.com": "Chris Zacharias",
  "https://www.stereogum.com": "Stereogum",
  "https://paulrobertlloyd.com": "Paul Robert Lloy",
  "https://www.ramijames.com": "Rami James",
  "https://connortumbleson.com": "Connor Tumbleson",
  "http://www.aaronsw.com": "Aaron Swartz",
  "https://tante.cc": "Jürgen Geuter",
  "https://www.404media.co": "T404 Media",
  "https://kevquirk.com": "Kev Quirk",
  "https://zacharylipez.ghost.io": "Zachary Lipez",
  "https://www.tbray.org": "Tim Bray",
  "https://alistapart.com": "A List Apart",
  "https://abookapart.com": "A Book ApartThe Wax and the Wane of the Web – ",
  "https://www.esquire.com": "Esquire",
  "https://anhvn.com": "Anh",
  "https://www.avclub.com": "The AV Club",
  "https://yatil.net": "Eric Eggert",
  "https://kyleshevlin.com": "Kyle Shevlin",
  "https://www.technologyreview.com": "MIT Technology Review",
  "https://www.alexhyett.com": "Alex Hyett",
  "https://nicolasgallagher.com": "Nicolas Gallagher",
  "https://mxstbr.com": "Max Stoiber",
  "https://disconnect.blog": "Paris Marx",
  "https://matthiasott.com": "Matthias Ott",
  "https://daught.me": "Nathaniel Daught",
  "https://www.vice.com": "Vice",
  "https://boehs.org": "Evan Boehs",
  "https://theinternet.review": "Jared White",
  "https://zeldman.com": "Jeffrey Zeldman",
  "https://gittings.studio": "Gittings Studio",
  "https://www.schneier.com": "Bruce Schneier",
  "https://adactio.com": "Jeremy Keith",
  "https://hidde.blog": "Hidde de Vries",
  "https://darthmall.net": "Evan Sheehan",
  "https://darnell.day": "Darnell Clayton",
  "https://chrisburnell.com": "Chris Burnell",
  "https://css-irl.info": "CSS { In Real Life }",
  "https://ishadeed.com": "Ahmad Shadeed",
  "https://theconversation.com": "Danielle Williams",
  "https://shellsharks.com": "Michael Sass",
  "https://www.independent.com": "Santa Barbara Independent",
  "https://lasso-security.webflow.io": "Lasso Security",
  "https://www.ellyloel.com": "Elly Loel",
  "https://www.thewrap.com": "Natalie Korach",
  "https://alan.norbauer.com": "Alan Norbauer",
  "https://tylersticka.com": "Tyler Sticka",
  "https://seirdy.one": "Rohan Kumar",
  "https://bored.horse": "Thord D. Hedengren",
  "https://underlap.org": "Glyn Normington",
  "https://theintercept.com": "The Intercept",
  "https://softwarecrisis.dev": "Baldur Bjarnason",
  "https://daverupert.com": "Dave Rupert",
  "https://www.aalto.fi": "Aalto University",
  "https://www.hollywoodreporter.com": "The Hollywood Reporter",
  "https://creativegood.com": "Creative Good",
  "https://scottwillsey.com": "Scott Willsey",
  "https://www.jeremiak.com": "Jeremia Kimelman",
  "https://bjhess.com": "Barry Hess",
  "https://www.sandofsky.com": "Benjamin Sandofsky",
  "https://www.noemamag.com": "Noema Magazine",
  "https://sixcolors.com" :"Six Colors",
  "https://www.sixcolors.com" :"Six Colors"
}