name: Scheduled blog posts to Linkedin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  linkedin_rss_job:
    runs-on: ubuntu-latest
    name: Post Latest RSS Post to Linkedin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Latest Post / Post On Linkedin
        uses: cdransf/Linkedin-RSS@main
        with:
          feed_list: https://coryd.dev/feeds/posts
          ln_access_token: ${{ secrets.LI_TOKEN }}
          embed_image: https://coryd.dev/assets/img/social-card.jpg