name: Broken link check

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 13 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check links on site
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://coryd.dev'
        include_url_prefix: 'https://coryd.dev'
        exclude_url_prefix: 'mailto,https://make.com'
        resolve_before_filtering: 'true'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5
        max_depth: 1